// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return web;
      /*throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );*/
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDBEQQ7VMiGYDZVvgnyRKQrvUZITt-Kr-I',
    appId: '1:432820316034:web:b6234bd0d16b2c2e1c919b',
    messagingSenderId: '432820316034',
    projectId: 'drugstore-v0-01',
    authDomain: 'drugstore-v0-01.firebaseapp.com',
    storageBucket: 'drugstore-v0-01.appspot.com',
    measurementId: 'G-M0G32JQYR8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDj6YU3sPTfcQ46xfNwD4nqVwhTmnTJ85U',
    appId: '1:432820316034:android:9e95547bb27629e31c919b',
    messagingSenderId: '432820316034',
    projectId: 'drugstore-v0-01',
    storageBucket: 'drugstore-v0-01.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCi3wXkI35y6L5eYREdWZlHV7t-EJwfj3c',
    appId: '1:432820316034:ios:711ed55c0609499a1c919b',
    messagingSenderId: '432820316034',
    projectId: 'drugstore-v0-01',
    storageBucket: 'drugstore-v0-01.appspot.com',
    iosBundleId: 'com.example.drugstore',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCi3wXkI35y6L5eYREdWZlHV7t-EJwfj3c',
    appId: '1:432820316034:ios:711ed55c0609499a1c919b',
    messagingSenderId: '432820316034',
    projectId: 'drugstore-v0-01',
    storageBucket: 'drugstore-v0-01.appspot.com',
    iosBundleId: 'com.example.drugstore',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDBEQQ7VMiGYDZVvgnyRKQrvUZITt-Kr-I',
    appId: '1:432820316034:web:f903d5b21f2aa4171c919b',
    messagingSenderId: '432820316034',
    projectId: 'drugstore-v0-01',
    authDomain: 'drugstore-v0-01.firebaseapp.com',
    storageBucket: 'drugstore-v0-01.appspot.com',
    measurementId: 'G-QL9T8JF6FD',
  );
}
